FPS = 60
ANCHO_PANTALLA = 1280
ALTO_PANTALLA = 720
HITBOX_JUGADOR = (80, 80)

GROUND_LEVEL = 650

# platforms.py
GROUND_COLLIDE_H = 5 # Aprox Gravedad/2 + 1
SIDE_COLLIDE_W = 10
DEBUG = True


# Prueba nivel
LEVEL_ONE = True


COOLDOWN_DISPARO = 500 
COOLDOWN_JUMP = 300